#!/usr/bin/env python3


# LD_LIBRARY_PATH=/home/anton/FEMFolder3/libs:/home/anton/FEMFolder3/my_libs
# export LD_LIBRARY_PATH


import os
import pprint
pprint = pprint.PrettyPrinter(indent=4).pprint
import shutil
import subprocess
import sys
import time


test_results_folder = 'results'


def main(libmesh_exe_folder='/home/anton/FEMFolder3',
         test_results_folder=test_results_folder):
    """
    Makes meshes for generated by create_systems.py .geo files.
    """
    # subprocess.call(['rm', '-rf', test_results_folder + '/meshes'])
    # subprocess.call(['rm', '-rf', test_results_folder + '/logs_gen_mesh'])
    if 'meshes' in os.listdir():
        print('error in create_meshes.py:',
              'meshes folder exists')
        return None
    exe_gen_mesh = libmesh_exe_folder + '/gen_mesh.x'
    log = open(test_results_folder + '/meshes_creation_log', 'w')
    subprocess.call(['mkdir', test_results_folder + '/meshes'])
    subprocess.call(['mkdir', test_results_folder + '/logs_gen_mesh'])
    fnames_per = os.listdir(test_results_folder + '/geo/per')
    fnames_irreg = os.listdir(test_results_folder + '/geo/irreg')
    for fname in fnames_per:
        log.write(fname + '\n')
        print(fname)
        f = open(test_results_folder + '/logs_gen_mesh/' + fname, 'w')
        code = subprocess.call([exe_gen_mesh,
                                test_results_folder + '/geo/per/' + fname,
                                '0.15', '2', '2'], stdout=f)
        vol_name = fname[:-3] + 'vol'
        shutil.copyfile('generated.vol',
                        test_results_folder + '/meshes/per_' + vol_name)
    for fname in fnames_irreg:
        log.write(fname + '\n')
        print(fname)
        f = open(test_results_folder + '/logs_gen_mesh/' + fname, 'w')
        code = subprocess.call([exe_gen_mesh,
                                test_results_folder + '/geo/per/' + fname,
                                '0.15', '2', '2'], stdout=f)
        vol_name = fname[:-3] + 'vol'
        shutil.copyfile('generated.vol',
                        test_results_folder + '/meshes/irreg_' + vol_name)
    subprocess.call(['rm', 'generated.vol'])


if __name__ == '__main__':
    main()
