#!/usr/bin/env python3


# LD_LIBRARY_PATH=/home/anton/FEMFolder3/libs:/home/anton/FEMFolder3/my_libs
# export LD_LIBRARY_PATH


import os
import pprint
pprint = pprint.PrettyPrinter(indent=4).pprint
import shutil
import subprocess
import sys
import time


test_results_folder = 'results'


def main(libmesh_exe_folder='/home/anton/FEMFolder3',
         test_results_folder='results'):
    """
    Makes meshes for generated by create_systems.py .geo files.
    """
    subprocess.call(['rm', '-rf', test_results_folder + '/meshes'])
    if 'meshes' in os.listdir():
        print('error in create_meshes.py:',
              'meshes folder exists')
        return None
    exe_gen_mesh = libmesh_exe_folder + '/gen_mesh.x'
    log = open(test_results_folder + '/meshes_creation_log', 'w')
    subprocess.call(['mkdir', test_results_folder + '/meshes'])
    subprocess.call(['mkdir', test_results_folder + '/logs_gen_mesh'])
    fnames = os.listdir(test_results_folder + '/geo')
    for fname in fnames:
        log.write(fname + '\n')
        print(fname)
        f = open(test_results_folder + '/logs_gen_mesh/' + fname, 'w')
        code = subprocess.call([exe_gen_mesh,
                                test_results_folder + '/geo/' + fname,
                                '0.15', '2', '2'], stdout=f)


if __name__ == '__main__':
    main()
